services:
  moya-frontend:
    container_name: moya-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/frontend
      - node_modules:/frontend/node_modules
      - nuxt:/frontend/.nuxt
    networks:
      - npm
      - moya-network
volumes:
  node_modules:
  nuxt:
networks:
  moya-network:
    driver: bridge
  npm:
    external: true
    name: npm
