services:
  moya-frontend:
    container_name: moya-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - npm
      - moya-network
networks:
  moya-network:
    driver: bridge
  npm:
    external: true
    name: npm
